-- Create products table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  category TEXT,
  image_url TEXT,
  stock INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Enable Row Level Security
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access
CREATE POLICY "Allow public read access" ON products FOR SELECT USING (true);

-- Create policy to allow authenticated insert/update/delete
-- Assuming using Supabase Auth. If you want to allow ANONYMOUS uploads (not recommended but easiest for quick demo if auth not set up), change to USING (true)
CREATE POLICY "Allow authenticated modifications" ON products FOR ALL USING (auth.role() = 'authenticated');

-- Create storage bucket for images
-- Note: You need to run this in the SQL editor, or create the bucket manually in the dashboard named 'products'
-- INSERT INTO storage.buckets (id, name, public) VALUES ('products', 'products', true);

-- Storage policies
-- CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id = 'products' );
-- CREATE POLICY "Auth Upload" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'products' AND auth.role() = 'authenticated' );
